In [9]:
import torch

In [10]:
x = torch.tensor(3.0, requires_grad=True)

In [11]:
y = x**2

In [12]:
y

tensor(9., grad_fn=<PowBackward0>)

In [13]:
y.backward()

In [14]:
x.grad

tensor(6.)

In [15]:
#
import math

def dz_dx(x):
    return 2 * x * math.cos(x**2)

In [16]:
dz_dx(3)

-5.466781571308061

In [17]:
x = torch.tensor(3.0, requires_grad=True)

In [32]:
def binary_cross_entropy_loss(y_pred, y):
    eplison = 1e-7
    prediction = torch.clamp(y_pred, eplison, 1 - eplison)
    return - (y * torch.log(prediction) + (1 - y) * torch.log(1 - prediction))

In [18]:
y = x ** 2
z = torch.sin(y)

In [19]:
y

tensor(9., grad_fn=<PowBackward0>)

In [20]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [21]:
z.backward()

In [22]:
x.grad

tensor(-5.4668)

In [36]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)


In [37]:
w

tensor(1., requires_grad=True)

In [38]:
b

tensor(0., requires_grad=True)

In [39]:
z = w*x + b


In [40]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [41]:
loss = binary_cross_entropy_loss(y_pred, y)

In [42]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [43]:
loss.backward()

In [46]:
b.grad

tensor(0.9988)

In [47]:
w.grad


tensor(6.6918)

In [48]:
# in vector
x = torch.tensor([6.7, 2.3, 4.5], requires_grad=True)

In [49]:
y = (x**2).mean()
y

tensor(23.4767, grad_fn=<MeanBackward0>)

In [50]:
y.backward()

In [51]:
x.grad

tensor([4.4667, 1.5333, 3.0000])

In [52]:
# cleaning up the gradients
x = torch.tensor([6.7, 2.3, 4.5], requires_grad=True)

In [63]:
y = (x**2).mean()


In [64]:
y.backward()

In [65]:
x.grad

tensor([4.4667, 1.5333, 3.0000])

In [66]:
x.grad.zero_()

tensor([0., 0., 0.])

In [73]:
# how to disable gradient tracking
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

x = torch.tensor(3.0, requires_grad=True)



In [74]:
x.requires_grad_(False)

tensor(3.)

In [75]:
y = x**2 
y

tensor(9.)

In [76]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [77]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2

z = x.detach()
y1 = z**2

In [78]:
y.backward()

In [79]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [80]:
x = torch.tensor(3.0, requires_grad=True)

with torch.no_grad():
    y = x**2
    y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn