In [1]:
import torch

print(torch.__version__)

2.12.0


In [4]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")

if torch.backends.mps.is_available():
    print("MPS is available. You can use Metal Performance Shaders for GPU acceleration on macOS.")

MPS is available. You can use Metal Performance Shaders for GPU acceleration on macOS.


In [6]:
#using empty
a =torch.empty(2,3)

In [8]:
#checking the type of tensor

print(a.type())

torch.FloatTensor


In [10]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using the rand
torch.rand(2,3)

tensor([[0.0726, 0.9926, 0.5253],
        [0.0842, 0.1963, 0.9949]])

In [13]:
# using of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [14]:
#using tensor

torch.tensor([1,2,3,4,5])


tensor([1, 2, 3, 4, 5])

In [17]:
#others
#arange
print("using arrange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,5))

#using eye
print("using eye ->", torch.eye(3,3))

using arrange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
