In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    

In [22]:
#create features and target
features = torch.rand(10, 5)  # 10 samples, 5 features

# create a model instance
model = Model(num_features=5)

model(features)



tensor([[0.6224],
        [0.6018],
        [0.5668],
        [0.5965],
        [0.5831],
        [0.5583],
        [0.5901],
        [0.5941],
        [0.6332],
        [0.6102]], grad_fn=<SigmoidBackward0>)

In [23]:
model.linear.weight

Parameter containing:
tensor([[ 0.0200,  0.1175,  0.2378, -0.2377,  0.1840]], requires_grad=True)

In [24]:
model.linear.bias

Parameter containing:
tensor([0.1897], requires_grad=True)

In [25]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [33]:
#create model
class NewModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
       
    def forward(self, features):
        out = self.network(features)
        return out

In [36]:
# create features and target
features = torch.rand(10, 5)  # 10 samples, 5 features

# create a model instance
new_model = NewModel(num_features=features.shape[1])
output = new_model(features)

output

tensor([[0.5090],
        [0.5239],
        [0.5211],
        [0.4707],
        [0.5261],
        [0.5180],
        [0.5099],
        [0.5215],
        [0.5180],
        [0.4838]], grad_fn=<SigmoidBackward0>)

In [ ]:
new_model.linear1.weight

Parameter containing:
tensor([[-0.0367, -0.1453,  0.4371, -0.2132,  0.1031],
        [-0.3825,  0.2537,  0.0823,  0.2827,  0.4438],
        [-0.2525, -0.3720, -0.1670, -0.1528,  0.3774]], requires_grad=True)

In [32]:
new_model.linear2.bias

Parameter containing:
tensor([-0.0074], requires_grad=True)

In [37]:
summary(new_model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
NewModel                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00